### ISSUE TITLE
"could not find requirejs" warning

### ISSUE THREAD

**Issue by socumbersome** [koka-lang/koka#4]
When in `koka's` interpreter, typing anything in gives "could not find requirejs" warning/error (twice), after which the normal result is printed, e.g.
```
> 2
could not find requirejs
could not find requirejs
2

>
```

On the other hand, typing in shell:
```
$ node out/lib/interactive.js
2
$ nodejs out/lib/interactive.js
2
$
```
So it doesn't complain about not being able to find `requirejs`.

On my PC, `node` is an alias for `nodejs`, and `nodejs` version is v4.2.6. Also, my `$NODE_PATH` is `/usr/local/lib/node_modules:/usr/local/lib/node_modules/requirejs`.
Setting `NODE_PATH` to `koka's` dir doesn't help.

How to get the warning go away?

**Comment by dhil** [comment]
I experienced a similar problem when using Koka on my Linux machine.

It seems that the function `joinPaths` in `File.hs` is broken whenever it joins an absolute path with relatives paths. Furthermore, the `visiblePackages` in `Package.hs` had a similar problem. Finally, it the function `codeGenJS` in `Compile.hs` wholly ignores the `node_modules` search path.

I implemented a rather hacky fix, which I recently made public at [https://github.com/dhil/koka/tree/fix-joinpaths](https://github.com/dhil/koka/tree/fix-joinpaths). Using this patch and
```
koka $ NODE_PATH=$(pwd)/node_modules jake test

[ output omitted ]
total tests: 252
tested     : 220
failed     : 1
total time : 84507ms
```
the only test that fails is `27: test/syntax/wrong/utf1.kk` which I suspect fails independently of the fix.

*Remark*: On my machine I have installed the required dependencies locally along side the compiler.

**Comment by socumbersome** [comment]
Thanks @dhil , your fix helps!
How about sending a pull request?

**Comment by dhil** [comment]
@socumbersome I am glad my fix could solve the issue. I will send a PR eventually, but my fix is rather quick. Ideally, I would like to make whole file path handling `File.hs` more robust across platforms. I hope to find time to generalise my fix sometime soon.

**Comment by osa1** [comment]
I'm also having the same problem. @dhil's patch improved the situation but test suite still doesn't completely pass (not sure if failures are related with this issue though).

**Comment by dhil** [comment]
Closing as #66 ought to have resolved this issue (and I can no longer reproduce the issue).
